POST http://0.0.0.0:42069/register
Content-Type: application/json

{
	"id": "12345678901",
	"name": "NEW TEST COMPANY",
	"employees": 1,
	"user_name":"test1@test.com",
	"user_password":"password123",
	"user_full_name":"TEST USER"
}
