POST http://0.0.0.0:42069/register
Content-Type: application/json

{
	"id": "1234567890",
	"name": "TEST COMPANY",
	"employees": 1,
	"user_name":"test@test.com",
	"user_password":"password123",
	"user_full_name":"TEST USER"
}
