GET http://0.0.0.0:42069/api/v1/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNGU4YTJjLTcwNjktNDQwMi04NjI1LWFkOGE2N2NkOTQzZiIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImNvbXBhbnlfaWQiOiJkZjVjMjYyYS0zZTA5LTQxNjktYjY2OC1iNzNiMDI5ZTM4ZDMiLCJpc19sb2dnZWRfaW4iOnRydWUsImlzc3VlZF9hdCI6IjIwMjMtMDktMjFUMjA6MzU6MDAuMjM2ODUwNjItMDU6MDAiLCJleHBpcmVkX2F0IjoiMjAyMy0wOS0yMVQyMTozNTowMC4yMzY4NTA5NjYtMDU6MDAifQ.2eFmz8w1ftPM-xy3uNsPNKR6fKyyXVuqBGR1oKhaEJ0
