GET http://0.0.0.0:42069/api/v1/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNGU4YTJjLTcwNjktNDQwMi04NjI1LWFkOGE2N2NkOTQzZiIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImNvbXBhbnlfaWQiOiJkZjVjMjYyYS0zZTA5LTQxNjktYjY2OC1iNzNiMDI5ZTM4ZDMiLCJpc19sb2dnZWRfaW4iOnRydWUsImlzc3VlZF9hdCI6IjIwMjMtMDktMjJUMTk6NDM6NTEuNzE1OTM5MDUxLTA1OjAwIiwiZXhwaXJlZF9hdCI6IjIwMjMtMDktMjJUMjA6NDM6NTEuNzE1OTM5MTItMDU6MDAifQ.YBvPEzky8JUz_6atVyXTUxzmOf6st18Xl16y1rD2ijg
