GET http://0.0.0.0:42069/api/v1/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNGU4YTJjLTcwNjktNDQwMi04NjI1LWFkOGE2N2NkOTQzZiIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImNvbXBhbnlfaWQiOiJkZjVjMjYyYS0zZTA5LTQxNjktYjY2OC1iNzNiMDI5ZTM4ZDMiLCJpc19sb2dnZWRfaW4iOnRydWUsImlzc3VlZF9hdCI6IjIwMjMtMDktMjNUMDg6MzA6MzYuMDgwNzYxMzY1LTA1OjAwIiwiZXhwaXJlZF9hdCI6IjIwMjMtMDktMjNUMDk6MzA6MzYuMDgwNzYxNjAzLTA1OjAwIn0.NFTRQ4demhzcGXgdbmk1agA0W1-ih4MVB-BGAY3F9WA
