PUT http://0.0.0.0:42069/api/v1/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNGU4YTJjLTcwNjktNDQwMi04NjI1LWFkOGE2N2NkOTQzZiIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImNvbXBhbnlfaWQiOiJkZjVjMjYyYS0zZTA5LTQxNjktYjY2OC1iNzNiMDI5ZTM4ZDMiLCJpc19sb2dnZWRfaW4iOnRydWUsImlzc3VlZF9hdCI6IjIwMjMtMDktMjJUMjE6MTY6NDguODQ5MjI3NzU4LTA1OjAwIiwiZXhwaXJlZF9hdCI6IjIwMjMtMDktMjJUMjI6MTY6NDguODQ5MjI4MTcxLTA1OjAwIn0.CORpk_ABdv5rDkj-gbkYuKhaYv3ldhdOVCxj0MPa1Io
