GET http://0.0.0.0:42069/api/v1/projects/50896342-42f5-4567-8ef6-6932c3cd8cbf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlYTI1N2Q0LTM2NDYtNGE1NC04N2NhLTIzZTkzMDUzYTBmMyIsImVtYWlsIjoidGVzdDFAdGVzdC5jb20iLCJjb21wYW55X2lkIjoiNmEzZGIyODQtZDE1YS00OGFkLWE1NGItODI4Njg5ZDc2NDAzIiwiaXNfbG9nZ2VkX2luIjp0cnVlLCJpc3N1ZWRfYXQiOiIyMDIzLTA5LTIzVDEzOjMxOjQ1LjA1OTE1NjMyOC0wNTowMCIsImV4cGlyZWRfYXQiOiIyMDIzLTA5LTIzVDE0OjMxOjQ1LjA1OTE1NjQwNS0wNTowMCJ9.GHwewuDOEJnwasjX91dEAWaodv4W00X76wboZZeGQsU
